"""Authoritative names and ordering for registered MCP tools."""

CREATE_DOCUMENT_TOOL = "create_document"
LIST_DOCUMENTS_TOOL = "list_documents"
GET_DOCUMENT_TOOL = "get_document"
SAVE_DOCUMENT_TOOL = "save_document"
LIST_OBJECTS_TOOL = "list_objects"
GET_OBJECT_TOOL = "get_object"
RECOMPUTE_DOCUMENT_TOOL = "recompute_document"
CREATE_BODY_TOOL = "create_body"

CREATE_SKETCH_TOOL = "create_sketch"
GET_SKETCH_TOOL = "get_sketch"
ADD_SKETCH_GEOMETRY_TOOL = "add_sketch_geometry"
ADD_SKETCH_CONSTRAINTS_TOOL = "add_sketch_constraints"
GET_DOCUMENT_HISTORY_TOOL = "get_document_history"
UNDO_DOCUMENT_TOOL = "undo_document"
REDO_DOCUMENT_TOOL = "redo_document"
CREATE_SKETCH_RECTANGLE_TOOL = "create_sketch_rectangle"
CREATE_SKETCH_CENTERED_RECTANGLE_TOOL = "create_sketch_centered_rectangle"
CREATE_SKETCH_EQUILATERAL_TRIANGLE_TOOL = "create_sketch_equilateral_triangle"
CREATE_SKETCH_REGULAR_POLYGON_TOOL = "create_sketch_regular_polygon"
CREATE_SKETCH_SLOT_TOOL = "create_sketch_slot"
CREATE_SKETCH_ROUNDED_RECTANGLE_TOOL = "create_sketch_rounded_rectangle"
ANALYZE_SKETCH_TOOL = "analyze_sketch"
VALIDATE_SKETCH_PROFILE_TOOL = "validate_sketch_profile"
LIST_SKETCH_OPEN_VERTICES_TOOL = "list_sketch_open_vertices"
ADD_EXTERNAL_GEOMETRY_TOOL = "add_external_geometry"
LIST_EXTERNAL_GEOMETRY_TOOL = "list_external_geometry"
REMOVE_EXTERNAL_GEOMETRY_TOOL = "remove_external_geometry"
GET_SKETCH_DEPENDENCIES_TOOL = "get_sketch_dependencies"
REMOVE_SKETCH_CONSTRAINTS_TOOL = "remove_sketch_constraints"
REMOVE_SKETCH_GEOMETRY_TOOL = "remove_sketch_geometry"
SET_SKETCH_GEOMETRY_CONSTRUCTION_TOOL = "set_sketch_geometry_construction"
UPDATE_SKETCH_GEOMETRY_TOOL = "update_sketch_geometry"
REPLACE_SKETCH_CONSTRAINT_TOOL = "replace_sketch_constraint"
UPDATE_SKETCH_CONSTRAINT_VALUE_TOOL = "update_sketch_constraint_value"
ADD_SKETCH_REFERENCE_CONSTRAINTS_TOOL = "add_sketch_reference_constraints"
SET_SKETCH_CONSTRAINT_NAME_TOOL = "set_sketch_constraint_name"
SET_SKETCH_CONSTRAINT_EXPRESSION_TOOL = "set_sketch_constraint_expression"
CLEAR_SKETCH_CONSTRAINT_EXPRESSION_TOOL = "clear_sketch_constraint_expression"
LIST_SKETCH_CONSTRAINT_EXPRESSIONS_TOOL = "list_sketch_constraint_expressions"
SET_SKETCH_CONSTRAINT_DRIVING_TOOL = "set_sketch_constraint_driving"
SET_SKETCH_CONSTRAINT_ACTIVE_TOOL = "set_sketch_constraint_active"
SET_SKETCH_CONSTRAINT_VIRTUAL_SPACE_TOOL = "set_sketch_constraint_virtual_space"
TRIM_SKETCH_GEOMETRY_TOOL = "trim_sketch_geometry"
SPLIT_SKETCH_GEOMETRY_TOOL = "split_sketch_geometry"
EXTEND_SKETCH_GEOMETRY_TOOL = "extend_sketch_geometry"
CHAMFER_SKETCH_GEOMETRY_TOOL = "chamfer_sketch_geometry"
FILLET_SKETCH_GEOMETRY_TOOL = "fillet_sketch_geometry"
MIRROR_SKETCH_GEOMETRY_TOOL = "mirror_sketch_geometry"
TRANSLATE_SKETCH_GEOMETRY_TOOL = "translate_sketch_geometry"
ROTATE_SKETCH_GEOMETRY_TOOL = "rotate_sketch_geometry"
SCALE_SKETCH_GEOMETRY_TOOL = "scale_sketch_geometry"
RECTANGULAR_ARRAY_SKETCH_GEOMETRY_TOOL = "rectangular_array_sketch_geometry"
POLAR_ARRAY_SKETCH_GEOMETRY_TOOL = "polar_array_sketch_geometry"

REGISTERED_TOOL_NAMES = (
    CREATE_DOCUMENT_TOOL,
    LIST_DOCUMENTS_TOOL,
    GET_DOCUMENT_TOOL,
    SAVE_DOCUMENT_TOOL,
    LIST_OBJECTS_TOOL,
    GET_OBJECT_TOOL,
    RECOMPUTE_DOCUMENT_TOOL,
    CREATE_BODY_TOOL,
    CREATE_SKETCH_TOOL,
    GET_SKETCH_TOOL,
    ADD_SKETCH_GEOMETRY_TOOL,
    ADD_SKETCH_CONSTRAINTS_TOOL,
    GET_DOCUMENT_HISTORY_TOOL,
    UNDO_DOCUMENT_TOOL,
    REDO_DOCUMENT_TOOL,
    CREATE_SKETCH_RECTANGLE_TOOL,
    CREATE_SKETCH_CENTERED_RECTANGLE_TOOL,
    CREATE_SKETCH_EQUILATERAL_TRIANGLE_TOOL,
    CREATE_SKETCH_REGULAR_POLYGON_TOOL,
    CREATE_SKETCH_SLOT_TOOL,
    CREATE_SKETCH_ROUNDED_RECTANGLE_TOOL,
    ANALYZE_SKETCH_TOOL,
    VALIDATE_SKETCH_PROFILE_TOOL,
    LIST_SKETCH_OPEN_VERTICES_TOOL,
    ADD_EXTERNAL_GEOMETRY_TOOL,
    LIST_EXTERNAL_GEOMETRY_TOOL,
    REMOVE_EXTERNAL_GEOMETRY_TOOL,
    GET_SKETCH_DEPENDENCIES_TOOL,
    REMOVE_SKETCH_CONSTRAINTS_TOOL,
    REMOVE_SKETCH_GEOMETRY_TOOL,
    SET_SKETCH_GEOMETRY_CONSTRUCTION_TOOL,
    UPDATE_SKETCH_GEOMETRY_TOOL,
    REPLACE_SKETCH_CONSTRAINT_TOOL,
    UPDATE_SKETCH_CONSTRAINT_VALUE_TOOL,
    ADD_SKETCH_REFERENCE_CONSTRAINTS_TOOL,
    SET_SKETCH_CONSTRAINT_NAME_TOOL,
    SET_SKETCH_CONSTRAINT_EXPRESSION_TOOL,
    CLEAR_SKETCH_CONSTRAINT_EXPRESSION_TOOL,
    LIST_SKETCH_CONSTRAINT_EXPRESSIONS_TOOL,
    TRIM_SKETCH_GEOMETRY_TOOL,
    SPLIT_SKETCH_GEOMETRY_TOOL,
    EXTEND_SKETCH_GEOMETRY_TOOL,
    CHAMFER_SKETCH_GEOMETRY_TOOL,
    FILLET_SKETCH_GEOMETRY_TOOL,
    MIRROR_SKETCH_GEOMETRY_TOOL,
    TRANSLATE_SKETCH_GEOMETRY_TOOL,
    ROTATE_SKETCH_GEOMETRY_TOOL,
    SCALE_SKETCH_GEOMETRY_TOOL,
    RECTANGULAR_ARRAY_SKETCH_GEOMETRY_TOOL,
    POLAR_ARRAY_SKETCH_GEOMETRY_TOOL,
    SET_SKETCH_CONSTRAINT_DRIVING_TOOL,
    SET_SKETCH_CONSTRAINT_ACTIVE_TOOL,
    SET_SKETCH_CONSTRAINT_VIRTUAL_SPACE_TOOL,
)
