"""Controlled public-facing labels for MCP-owned FreeCAD transactions."""

CREATE_BODY_TRANSACTION_NAME = "Create body"
CREATE_SKETCH_TRANSACTION_NAME = "Create sketch"
ADD_SKETCH_GEOMETRY_TRANSACTION_NAME = "Add sketch geometry"
ADD_SKETCH_CONSTRAINTS_TRANSACTION_NAME = "Add sketch constraints"
ADD_SKETCH_REFERENCE_CONSTRAINTS_TRANSACTION_NAME = "Add sketch reference constraints"
ADD_SKETCH_EXTERNAL_GEOMETRY_TRANSACTION_NAME = "Add sketch external geometry"
REMOVE_SKETCH_EXTERNAL_GEOMETRY_TRANSACTION_NAME = "Remove sketch external geometry"
CREATE_SKETCH_RECTANGLE_TRANSACTION_NAME = "Create sketch rectangle"
CREATE_SKETCH_CENTERED_RECTANGLE_TRANSACTION_NAME = "Create centered sketch rectangle"
CREATE_SKETCH_EQUILATERAL_TRIANGLE_TRANSACTION_NAME = "Create sketch equilateral triangle"
CREATE_SKETCH_REGULAR_POLYGON_TRANSACTION_NAME = "Create sketch regular polygon"
CREATE_SKETCH_SLOT_TRANSACTION_NAME = "Create sketch slot"
CREATE_SKETCH_ROUNDED_RECTANGLE_TRANSACTION_NAME = "Create sketch rounded rectangle"
REMOVE_SKETCH_CONSTRAINTS_TRANSACTION_NAME = "Remove sketch constraints"
REMOVE_SKETCH_GEOMETRY_TRANSACTION_NAME = "Remove sketch geometry"
SET_SKETCH_GEOMETRY_CONSTRUCTION_TRANSACTION_NAME = "Set sketch geometry construction"
UPDATE_SKETCH_GEOMETRY_TRANSACTION_NAME = "Update sketch geometry"
REPLACE_SKETCH_CONSTRAINT_TRANSACTION_NAME = "Replace sketch constraint"
UPDATE_SKETCH_CONSTRAINT_VALUE_TRANSACTION_NAME = "Update sketch constraint value"
SET_SKETCH_CONSTRAINT_NAME_TRANSACTION_NAME = "Set sketch constraint name"
SET_SKETCH_CONSTRAINT_EXPRESSION_TRANSACTION_NAME = "Set sketch constraint expression"
CLEAR_SKETCH_CONSTRAINT_EXPRESSION_TRANSACTION_NAME = "Clear sketch constraint expression"

CONTROLLED_TRANSACTION_NAMES = (
    CREATE_BODY_TRANSACTION_NAME,
    CREATE_SKETCH_TRANSACTION_NAME,
    ADD_SKETCH_GEOMETRY_TRANSACTION_NAME,
    ADD_SKETCH_CONSTRAINTS_TRANSACTION_NAME,
    ADD_SKETCH_REFERENCE_CONSTRAINTS_TRANSACTION_NAME,
    ADD_SKETCH_EXTERNAL_GEOMETRY_TRANSACTION_NAME,
    REMOVE_SKETCH_EXTERNAL_GEOMETRY_TRANSACTION_NAME,
    CREATE_SKETCH_RECTANGLE_TRANSACTION_NAME,
    CREATE_SKETCH_CENTERED_RECTANGLE_TRANSACTION_NAME,
    CREATE_SKETCH_EQUILATERAL_TRIANGLE_TRANSACTION_NAME,
    CREATE_SKETCH_REGULAR_POLYGON_TRANSACTION_NAME,
    CREATE_SKETCH_SLOT_TRANSACTION_NAME,
    CREATE_SKETCH_ROUNDED_RECTANGLE_TRANSACTION_NAME,
    REMOVE_SKETCH_CONSTRAINTS_TRANSACTION_NAME,
    REMOVE_SKETCH_GEOMETRY_TRANSACTION_NAME,
    SET_SKETCH_GEOMETRY_CONSTRUCTION_TRANSACTION_NAME,
    UPDATE_SKETCH_GEOMETRY_TRANSACTION_NAME,
    REPLACE_SKETCH_CONSTRAINT_TRANSACTION_NAME,
    UPDATE_SKETCH_CONSTRAINT_VALUE_TRANSACTION_NAME,
    SET_SKETCH_CONSTRAINT_NAME_TRANSACTION_NAME,
    SET_SKETCH_CONSTRAINT_EXPRESSION_TRANSACTION_NAME,
    CLEAR_SKETCH_CONSTRAINT_EXPRESSION_TRANSACTION_NAME,
)

__all__ = [
    "ADD_SKETCH_CONSTRAINTS_TRANSACTION_NAME",
    "ADD_SKETCH_EXTERNAL_GEOMETRY_TRANSACTION_NAME",
    "ADD_SKETCH_GEOMETRY_TRANSACTION_NAME",
    "ADD_SKETCH_REFERENCE_CONSTRAINTS_TRANSACTION_NAME",
    "CLEAR_SKETCH_CONSTRAINT_EXPRESSION_TRANSACTION_NAME",
    "CONTROLLED_TRANSACTION_NAMES",
    "CREATE_BODY_TRANSACTION_NAME",
    "CREATE_SKETCH_CENTERED_RECTANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_EQUILATERAL_TRIANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_RECTANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_REGULAR_POLYGON_TRANSACTION_NAME",
    "CREATE_SKETCH_ROUNDED_RECTANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_SLOT_TRANSACTION_NAME",
    "CREATE_SKETCH_TRANSACTION_NAME",
    "REMOVE_SKETCH_CONSTRAINTS_TRANSACTION_NAME",
    "REMOVE_SKETCH_EXTERNAL_GEOMETRY_TRANSACTION_NAME",
    "REMOVE_SKETCH_GEOMETRY_TRANSACTION_NAME",
    "SET_SKETCH_CONSTRAINT_EXPRESSION_TRANSACTION_NAME",
    "SET_SKETCH_CONSTRAINT_NAME_TRANSACTION_NAME",
    "SET_SKETCH_GEOMETRY_CONSTRUCTION_TRANSACTION_NAME",
]
