"""Controlled public-facing labels for MCP-owned FreeCAD transactions."""

CREATE_BODY_TRANSACTION_NAME = "Create body"
CREATE_SKETCH_TRANSACTION_NAME = "Create sketch"
ADD_SKETCH_GEOMETRY_TRANSACTION_NAME = "Add sketch geometry"
ADD_SKETCH_CONSTRAINTS_TRANSACTION_NAME = "Add sketch constraints"
CREATE_SKETCH_RECTANGLE_TRANSACTION_NAME = "Create sketch rectangle"
CREATE_SKETCH_CENTERED_RECTANGLE_TRANSACTION_NAME = "Create centered sketch rectangle"
CREATE_SKETCH_EQUILATERAL_TRIANGLE_TRANSACTION_NAME = "Create sketch equilateral triangle"
CREATE_SKETCH_REGULAR_POLYGON_TRANSACTION_NAME = "Create sketch regular polygon"

CONTROLLED_TRANSACTION_NAMES = (
    CREATE_BODY_TRANSACTION_NAME,
    CREATE_SKETCH_TRANSACTION_NAME,
    ADD_SKETCH_GEOMETRY_TRANSACTION_NAME,
    ADD_SKETCH_CONSTRAINTS_TRANSACTION_NAME,
    CREATE_SKETCH_RECTANGLE_TRANSACTION_NAME,
    CREATE_SKETCH_CENTERED_RECTANGLE_TRANSACTION_NAME,
    CREATE_SKETCH_EQUILATERAL_TRIANGLE_TRANSACTION_NAME,
    CREATE_SKETCH_REGULAR_POLYGON_TRANSACTION_NAME,
)

__all__ = [
    "ADD_SKETCH_CONSTRAINTS_TRANSACTION_NAME",
    "ADD_SKETCH_GEOMETRY_TRANSACTION_NAME",
    "CONTROLLED_TRANSACTION_NAMES",
    "CREATE_BODY_TRANSACTION_NAME",
    "CREATE_SKETCH_CENTERED_RECTANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_EQUILATERAL_TRIANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_RECTANGLE_TRANSACTION_NAME",
    "CREATE_SKETCH_REGULAR_POLYGON_TRANSACTION_NAME",
    "CREATE_SKETCH_TRANSACTION_NAME",
]
