"""The single authoritative human-readable public tool catalogue."""

from __future__ import annotations

from dataclasses import dataclass

from freecad_mcp.catalog.groups import ToolGroup, ToolSection


@dataclass(frozen=True, slots=True)
class ToolDefinition:
    """Stable public identity plus logical catalogue metadata."""

    name: str
    title: str
    group: ToolGroup
    section: ToolSection
    logical_order: int
    legacy_wire_order: int


def _tool(
    name: str,
    title: str,
    group: ToolGroup,
    section: ToolSection,
    logical_order: int,
    legacy_wire_order: int,
) -> ToolDefinition:
    return ToolDefinition(
        name=name,
        title=title,
        group=group,
        section=section,
        logical_order=logical_order,
        legacy_wire_order=legacy_wire_order,
    )


TOOL_DEFINITIONS = (
    _tool(
        "create_document",
        "Create document",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        1,
        1,
    ),
    _tool(
        "list_documents",
        "List open documents",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        2,
        2,
    ),
    _tool(
        "get_document",
        "Get document",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        3,
        3,
    ),
    _tool(
        "list_objects",
        "List document objects",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        4,
        5,
    ),
    _tool(
        "get_object",
        "Get document object",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        5,
        6,
    ),
    _tool(
        "recompute_document",
        "Recompute document",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        6,
        7,
    ),
    _tool(
        "save_document",
        "Save document",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_LIFECYCLE,
        7,
        4,
    ),
    _tool(
        "get_document_history",
        "Get document history",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_HISTORY,
        8,
        13,
    ),
    _tool(
        "undo_document",
        "Undo document transaction",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_HISTORY,
        9,
        14,
    ),
    _tool(
        "redo_document",
        "Redo document transaction",
        ToolGroup.DOCUMENT,
        ToolSection.DOCUMENT_HISTORY,
        10,
        15,
    ),
    _tool(
        "create_body",
        "Create Part Design body",
        ToolGroup.PART_DESIGN,
        ToolSection.BODY_LIFECYCLE,
        11,
        8,
    ),
    _tool(
        "create_sketch",
        "Create sketch",
        ToolGroup.SKETCHER,
        ToolSection.SKETCH_LIFECYCLE_AND_INSPECTION,
        12,
        9,
    ),
    _tool(
        "get_sketch",
        "Get sketch",
        ToolGroup.SKETCHER,
        ToolSection.SKETCH_LIFECYCLE_AND_INSPECTION,
        13,
        10,
    ),
    _tool(
        "get_sketch_dependencies",
        "Get sketch dependencies",
        ToolGroup.SKETCHER,
        ToolSection.SKETCH_LIFECYCLE_AND_INSPECTION,
        14,
        29,
    ),
    _tool(
        "add_sketch_geometry",
        "Add sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        15,
        11,
    ),
    _tool(
        "create_sketch_polyline",
        "Create sketch polyline",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        16,
        22,
    ),
    _tool(
        "create_sketch_rectangle",
        "Create sketch rectangle",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        17,
        16,
    ),
    _tool(
        "create_sketch_centered_rectangle",
        "Create centred sketch rectangle",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        18,
        17,
    ),
    _tool(
        "create_sketch_rounded_rectangle",
        "Create rounded sketch rectangle",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        19,
        21,
    ),
    _tool(
        "create_sketch_equilateral_triangle",
        "Create equilateral sketch triangle",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        20,
        18,
    ),
    _tool(
        "create_sketch_regular_polygon",
        "Create regular sketch polygon",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        21,
        19,
    ),
    _tool(
        "create_sketch_slot",
        "Create sketch slot",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_AND_PROFILE_CREATION,
        22,
        20,
    ),
    _tool(
        "set_sketch_geometry_construction",
        "Set sketch geometry construction state",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_STATE_AND_EDITING,
        23,
        32,
    ),
    _tool(
        "update_sketch_geometry",
        "Update sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_STATE_AND_EDITING,
        24,
        33,
    ),
    _tool(
        "remove_sketch_geometry",
        "Remove sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.GEOMETRY_STATE_AND_EDITING,
        25,
        31,
    ),
    _tool(
        "add_external_geometry",
        "Add sketch external geometry",
        ToolGroup.SKETCHER,
        ToolSection.EXTERNAL_GEOMETRY,
        26,
        26,
    ),
    _tool(
        "list_external_geometry",
        "List sketch external geometry",
        ToolGroup.SKETCHER,
        ToolSection.EXTERNAL_GEOMETRY,
        27,
        27,
    ),
    _tool(
        "remove_external_geometry",
        "Remove sketch external geometry",
        ToolGroup.SKETCHER,
        ToolSection.EXTERNAL_GEOMETRY,
        28,
        28,
    ),
    _tool(
        "add_sketch_constraints",
        "Add sketch constraints",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        29,
        12,
    ),
    _tool(
        "add_sketch_reference_constraints",
        "Add sketch reference constraints",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        30,
        36,
    ),
    _tool(
        "replace_sketch_constraint",
        "Replace sketch constraint",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        31,
        34,
    ),
    _tool(
        "update_sketch_constraint_value",
        "Update sketch constraint value",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        32,
        35,
    ),
    _tool(
        "set_sketch_constraint_driving",
        "Set sketch constraint driving state",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        33,
        52,
    ),
    _tool(
        "set_sketch_constraint_active",
        "Set sketch constraint active state",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        34,
        53,
    ),
    _tool(
        "set_sketch_constraint_virtual_space",
        "Set sketch constraint virtual-space state",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        35,
        54,
    ),
    _tool(
        "set_sketch_constraint_name",
        "Set sketch constraint name",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        36,
        37,
    ),
    _tool(
        "list_sketch_constraint_expressions",
        "List sketch constraint expressions",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        37,
        40,
    ),
    _tool(
        "set_sketch_constraint_expression",
        "Set sketch constraint expression",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        38,
        38,
    ),
    _tool(
        "clear_sketch_constraint_expression",
        "Clear sketch constraint expression",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        39,
        39,
    ),
    _tool(
        "remove_sketch_constraints",
        "Remove sketch constraints",
        ToolGroup.SKETCHER,
        ToolSection.CONSTRAINTS,
        40,
        30,
    ),
    _tool(
        "analyze_sketch",
        "Analyse sketch topology",
        ToolGroup.SKETCHER,
        ToolSection.ANALYSIS_AND_VALIDATION,
        41,
        23,
    ),
    _tool(
        "validate_sketch_profile",
        "Validate sketch profile",
        ToolGroup.SKETCHER,
        ToolSection.ANALYSIS_AND_VALIDATION,
        42,
        24,
    ),
    _tool(
        "list_sketch_open_vertices",
        "List open sketch vertices",
        ToolGroup.SKETCHER,
        ToolSection.ANALYSIS_AND_VALIDATION,
        43,
        25,
    ),
    _tool(
        "analyze_sketch_constraints",
        "Analyse sketch constraints",
        ToolGroup.SKETCHER,
        ToolSection.ANALYSIS_AND_VALIDATION,
        44,
        59,
    ),
    _tool(
        "diagnose_sketch_dof",
        "Diagnose sketch degrees of freedom",
        ToolGroup.SKETCHER,
        ToolSection.ANALYSIS_AND_VALIDATION,
        45,
        60,
    ),
    _tool(
        "trim_sketch_geometry",
        "Trim sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.TOPOLOGY_EDITING,
        46,
        41,
    ),
    _tool(
        "extend_sketch_geometry",
        "Extend sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.TOPOLOGY_EDITING,
        47,
        43,
    ),
    _tool(
        "split_sketch_geometry",
        "Split sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.TOPOLOGY_EDITING,
        48,
        42,
    ),
    _tool(
        "chamfer_sketch_geometry",
        "Chamfer sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.TOPOLOGY_EDITING,
        49,
        44,
    ),
    _tool(
        "fillet_sketch_geometry",
        "Fillet sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.TOPOLOGY_EDITING,
        50,
        45,
    ),
    _tool(
        "translate_sketch_geometry",
        "Translate sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.SELECTED_GEOMETRY_TRANSFORMS_AND_ARRAYS,
        51,
        47,
    ),
    _tool(
        "rotate_sketch_geometry",
        "Rotate sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.SELECTED_GEOMETRY_TRANSFORMS_AND_ARRAYS,
        52,
        48,
    ),
    _tool(
        "scale_sketch_geometry",
        "Scale sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.SELECTED_GEOMETRY_TRANSFORMS_AND_ARRAYS,
        53,
        49,
    ),
    _tool(
        "mirror_sketch_geometry",
        "Mirror sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.SELECTED_GEOMETRY_TRANSFORMS_AND_ARRAYS,
        54,
        46,
    ),
    _tool(
        "rectangular_array_sketch_geometry",
        "Create rectangular array of sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.SELECTED_GEOMETRY_TRANSFORMS_AND_ARRAYS,
        55,
        50,
    ),
    _tool(
        "polar_array_sketch_geometry",
        "Create polar array of sketch geometry",
        ToolGroup.SKETCHER,
        ToolSection.SELECTED_GEOMETRY_TRANSFORMS_AND_ARRAYS,
        56,
        51,
    ),
    _tool(
        "translate_sketch",
        "Translate whole sketch",
        ToolGroup.SKETCHER,
        ToolSection.WHOLE_SKETCH_TRANSFORMS,
        57,
        55,
    ),
    _tool(
        "rotate_sketch",
        "Rotate whole sketch",
        ToolGroup.SKETCHER,
        ToolSection.WHOLE_SKETCH_TRANSFORMS,
        58,
        56,
    ),
    _tool(
        "scale_sketch",
        "Scale whole sketch",
        ToolGroup.SKETCHER,
        ToolSection.WHOLE_SKETCH_TRANSFORMS,
        59,
        57,
    ),
    _tool(
        "mirror_sketch",
        "Mirror whole sketch",
        ToolGroup.SKETCHER,
        ToolSection.WHOLE_SKETCH_TRANSFORMS,
        60,
        58,
    ),
)


__all__ = ["TOOL_DEFINITIONS", "ToolDefinition"]
